-- #474 indoor mission canonical server state

create table if not exists public.indoor_mission_templates (
  id text primary key,
  category text not null,
  title text not null,
  description text not null,
  minimum_action_count integer not null check (minimum_action_count > 0),
  base_reward_points integer not null check (base_reward_points >= 0),
  streak_eligible boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.owner_indoor_mission_daily_state (
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  day_key date not null,
  pet_context_id text not null,
  pet_name_snapshot text not null default '강아지',
  age_years integer,
  age_band text not null default 'unknown',
  activity_level text not null default 'moderate',
  walk_frequency text not null default 'steady',
  applied_multiplier double precision not null default 1.0 check (applied_multiplier >= 0.75 and applied_multiplier <= 1.25),
  adjustment_description text not null default '기본 난이도 유지',
  adjustment_reasons jsonb not null default '[]'::jsonb,
  easy_day_applied boolean not null default false,
  easy_day_activated_at timestamptz,
  extension_state text not null default 'none',
  extension_source_day_key date,
  extension_source_instance_id uuid,
  base_risk_level text not null default 'clear',
  effective_risk_level text not null default 'clear',
  refreshed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (owner_user_id, day_key, pet_context_id)
);

create table if not exists public.owner_indoor_mission_instances (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  day_key date not null,
  pet_context_id text not null,
  instance_key text not null unique,
  template_id text not null references public.indoor_mission_templates(id) on delete restrict,
  category text not null,
  title_snapshot text not null,
  description_snapshot text not null,
  minimum_action_count_snapshot integer not null check (minimum_action_count_snapshot > 0),
  reward_points_snapshot integer not null check (reward_points_snapshot >= 0),
  streak_eligible_snapshot boolean not null,
  action_count integer not null default 0 check (action_count >= 0),
  status text not null default 'active',
  is_extension boolean not null default false,
  extension_source_day_key date,
  extension_reward_scale double precision not null default 1.0,
  claimed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.owner_indoor_mission_action_events (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  mission_instance_id uuid not null references public.owner_indoor_mission_instances(id) on delete cascade,
  event_id text not null,
  delta_value integer not null default 1 check (delta_value > 0),
  payload jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (mission_instance_id, event_id)
);

create table if not exists public.owner_indoor_mission_claims (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  mission_instance_id uuid not null unique references public.owner_indoor_mission_instances(id) on delete cascade,
  request_id text not null,
  claim_status text not null default 'claimed',
  reward_points integer not null check (reward_points >= 0),
  claimed_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_owner_indoor_mission_claims_owner_request
  on public.owner_indoor_mission_claims(owner_user_id, request_id);
create index if not exists idx_owner_indoor_mission_state_owner_day
  on public.owner_indoor_mission_daily_state(owner_user_id, day_key desc, pet_context_id);
create index if not exists idx_owner_indoor_mission_instances_owner_day
  on public.owner_indoor_mission_instances(owner_user_id, day_key desc, pet_context_id, status);
create index if not exists idx_owner_indoor_mission_instances_extension_source
  on public.owner_indoor_mission_daily_state(owner_user_id, extension_source_instance_id);
create index if not exists idx_owner_indoor_mission_action_events_owner_recorded
  on public.owner_indoor_mission_action_events(owner_user_id, recorded_at desc);

alter table public.indoor_mission_templates enable row level security;
alter table public.owner_indoor_mission_daily_state enable row level security;
alter table public.owner_indoor_mission_instances enable row level security;
alter table public.owner_indoor_mission_action_events enable row level security;
alter table public.owner_indoor_mission_claims enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'indoor_mission_templates' and policyname = 'indoor_mission_templates_public_select'
  ) then
    create policy indoor_mission_templates_public_select
      on public.indoor_mission_templates
      for select
      to authenticated
      using (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'indoor_mission_templates' and policyname = 'indoor_mission_templates_service_write'
  ) then
    create policy indoor_mission_templates_service_write
      on public.indoor_mission_templates
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;

do $$
declare
  table_name text;
  policy_prefix text;
begin
  foreach table_name in array array[
    'owner_indoor_mission_daily_state',
    'owner_indoor_mission_instances',
    'owner_indoor_mission_action_events',
    'owner_indoor_mission_claims'
  ]
  loop
    policy_prefix := table_name;
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = table_name and policyname = policy_prefix || '_owner_select'
    ) then
      execute format(
        'create policy %I on public.%I for select to authenticated using (owner_user_id = auth.uid())',
        policy_prefix || '_owner_select',
        table_name
      );
    end if;
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = table_name and policyname = policy_prefix || '_service_write'
    ) then
      execute format(
        'create policy %I on public.%I for all to service_role using (true) with check (true)',
        policy_prefix || '_service_write',
        table_name
      );
    end if;
  end loop;
end $$;

drop trigger if exists trg_indoor_mission_templates_updated_at on public.indoor_mission_templates;
create trigger trg_indoor_mission_templates_updated_at
before update on public.indoor_mission_templates
for each row execute function public.set_updated_at();

drop trigger if exists trg_owner_indoor_mission_daily_state_updated_at on public.owner_indoor_mission_daily_state;
create trigger trg_owner_indoor_mission_daily_state_updated_at
before update on public.owner_indoor_mission_daily_state
for each row execute function public.set_updated_at();

drop trigger if exists trg_owner_indoor_mission_instances_updated_at on public.owner_indoor_mission_instances;
create trigger trg_owner_indoor_mission_instances_updated_at
before update on public.owner_indoor_mission_instances
for each row execute function public.set_updated_at();

drop trigger if exists trg_owner_indoor_mission_claims_updated_at on public.owner_indoor_mission_claims;
create trigger trg_owner_indoor_mission_claims_updated_at
before update on public.owner_indoor_mission_claims
for each row execute function public.set_updated_at();

insert into public.indoor_mission_templates (
  id,
  category,
  title,
  description,
  minimum_action_count,
  base_reward_points,
  streak_eligible,
  is_active,
  metadata
)
values
  (
    'indoor.record.cleanup',
    'recordCleanup',
    '기록 정리 체크',
    '산책 기록/사진/메모 정리를 3회 진행해요.',
    3,
    40,
    true,
    true,
    jsonb_build_object('source', 'IndoorMissionStore')
  ),
  (
    'indoor.petcare.check',
    'petCareCheck',
    '펫 케어 루틴 체크',
    '물/브러싱/컨디션 체크를 2회 진행해요.',
    2,
    32,
    true,
    true,
    jsonb_build_object('source', 'IndoorMissionStore')
  ),
  (
    'indoor.training.check',
    'trainingCheck',
    '실내 훈련 체크',
    '기다려/손/하우스 훈련을 4회 수행해요.',
    4,
    48,
    true,
    true,
    jsonb_build_object('source', 'IndoorMissionStore')
  ),
  (
    'indoor.record.photo_sort',
    'recordCleanup',
    '사진 정리 체크',
    '최근 산책 사진 분류/삭제/보관을 2회 진행해요.',
    2,
    28,
    true,
    true,
    jsonb_build_object('source', 'IndoorMissionStore')
  ),
  (
    'indoor.training.focus',
    'trainingCheck',
    '집중 훈련 체크',
    '10초 집중 유지 훈련을 3회 진행해요.',
    3,
    36,
    true,
    true,
    jsonb_build_object('source', 'IndoorMissionStore')
  )
on conflict (id) do update
set
  category = excluded.category,
  title = excluded.title,
  description = excluded.description,
  minimum_action_count = excluded.minimum_action_count,
  base_reward_points = excluded.base_reward_points,
  streak_eligible = excluded.streak_eligible,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  updated_at = now();

create or replace function public.normalize_indoor_mission_pet_context_id(raw text)
returns text
language sql
immutable
as $$
  select coalesce(nullif(trim(raw), ''), '__none__');
$$;

create or replace function public.normalize_indoor_mission_day_key(raw text, now_ts timestamptz default now())
returns date
language sql
stable
as $$
  select coalesce(
    to_date(nullif(trim(raw), ''), 'YYYY-MM-DD'),
    (timezone('utc', now_ts))::date
  );
$$;

create or replace function public.indoor_mission_replacement_count(risk text)
returns integer
language sql
immutable
as $$
  select case public.normalize_indoor_weather_risk(risk)
    when 'caution' then 1
    when 'bad' then 2
    when 'severe' then 3
    else 0
  end;
$$;

create or replace function public.indoor_mission_reward_scale(risk text)
returns double precision
language sql
immutable
as $$
  select case public.normalize_indoor_weather_risk(risk)
    when 'caution' then 0.92
    when 'bad' then 0.88
    when 'severe' then 0.84
    else 1.0
  end;
$$;

create or replace function public.indoor_mission_age_band(age_years integer)
returns text
language sql
immutable
as $$
  select case
    when age_years is null then 'unknown'
    when age_years <= 1 then 'puppy'
    when age_years >= 10 then 'senior'
    else 'adult'
  end;
$$;

create or replace function public.indoor_mission_activity_level(recent_daily_minutes double precision)
returns text
language sql
immutable
as $$
  select case
    when coalesce(recent_daily_minutes, 0) < 20 then 'low'
    when coalesce(recent_daily_minutes, 0) > 65 then 'high'
    else 'moderate'
  end;
$$;

create or replace function public.indoor_mission_walk_frequency_band(average_weekly_walk_count double precision)
returns text
language sql
immutable
as $$
  select case
    when coalesce(average_weekly_walk_count, 0) < 3 then 'sparse'
    when coalesce(average_weekly_walk_count, 0) > 10 then 'frequent'
    else 'steady'
  end;
$$;

create or replace function public.indoor_mission_template_priority(category text, risk text)
returns integer
language sql
immutable
as $$
  select case public.normalize_indoor_weather_risk(risk)
    when 'caution' then case category
      when 'petCareCheck' then 0
      when 'recordCleanup' then 1
      when 'trainingCheck' then 2
      else 99
    end
    when 'bad' then case category
      when 'recordCleanup' then 0
      when 'petCareCheck' then 1
      when 'trainingCheck' then 2
      else 99
    end
    when 'severe' then case category
      when 'petCareCheck' then 0
      when 'trainingCheck' then 1
      when 'recordCleanup' then 2
      else 99
    end
    else 99
  end;
$$;

create or replace function public.indoor_mission_extension_message(state text)
returns text
language sql
immutable
as $$
  select case lower(coalesce(state, 'none'))
    when 'active' then '전일 미션 1개를 자동 연장했어요. 완료 시 보상은 기본의 70%만 지급돼요.'
    when 'consumed' then '연장 슬롯 사용 완료. 연장 미션은 시즌 점수/연속 보상에서 제외돼요.'
    when 'expired' then '전일 연장 미션이 미완료로 소멸되어 오늘은 자동 연장이 제공되지 않아요.'
    when 'cooldown' then '연장 슬롯은 연속 2일 이상 자동 적용되지 않아요. 오늘은 쿨다운 상태예요.'
    else null
  end;
$$;

create or replace function public.indoor_mission_easy_day_message(applied boolean)
returns text
language sql
immutable
as $$
  select case when coalesce(applied, false)
    then '오늘 쉬운 날 모드가 적용되어 보상이 20% 감액돼요.'
    else '쉬운 날 모드(일 1회) 사용 시 오늘 목표를 더 쉽게 진행하고 보상은 20% 감액돼요.'
  end;
$$;

create or replace function public.rpc_get_indoor_mission_summary(payload jsonb)
returns table (
  owner_user_id uuid,
  pet_context_id text,
  day_key text,
  base_risk_level text,
  effective_risk_level text,
  extension_state text,
  extension_message text,
  pet_name text,
  age_band text,
  activity_level text,
  walk_frequency text,
  applied_multiplier double precision,
  adjustment_description text,
  adjustment_reasons jsonb,
  easy_day_state text,
  easy_day_message text,
  history jsonb,
  missions jsonb,
  refreshed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_uid uuid := auth.uid();
  resolved_now_ts timestamptz := coalesce(
    nullif(payload ->> 'now_ts', '')::timestamptz,
    nullif(payload ->> 'in_now_ts', '')::timestamptz,
    now()
  );
  resolved_day date := public.normalize_indoor_mission_day_key(
    coalesce(payload ->> 'day_key', payload ->> 'in_day_key'),
    resolved_now_ts
  );
  resolved_pet_context_id text := public.normalize_indoor_mission_pet_context_id(
    coalesce(payload ->> 'pet_context_id', payload ->> 'in_pet_context_id')
  );
  resolved_pet_name text := coalesce(nullif(trim(coalesce(payload ->> 'pet_name', payload ->> 'in_pet_name')), ''), '강아지');
  resolved_age_years integer := nullif(trim(coalesce(payload ->> 'age_years', payload ->> 'in_age_years')), '')::integer;
  resolved_recent_daily_minutes double precision := greatest(coalesce(nullif(trim(coalesce(payload ->> 'recent_daily_minutes', payload ->> 'in_recent_daily_minutes')), '')::double precision, 0), 0);
  resolved_average_weekly_walk_count double precision := greatest(coalesce(nullif(trim(coalesce(payload ->> 'average_weekly_walk_count', payload ->> 'in_average_weekly_walk_count')), '')::double precision, 0), 0);
  requested_base_risk text := public.normalize_indoor_weather_risk(
    coalesce(
      nullif(trim(coalesce(payload ->> 'base_risk_level', payload ->> 'in_base_risk_level')), ''),
      'clear'
    )
  );
  weather_row record;
  effective_risk_value text := 'clear';
  replacement_count_value integer := 0;
  previous_multiplier double precision := null;
  age_band_value text := 'unknown';
  activity_level_value text := 'moderate';
  walk_frequency_value text := 'steady';
  multiplier_value double precision := 1.0;
  clamped_multiplier_value double precision := 1.0;
  adjustment_description_value text := '기본 난이도 유지';
  adjustment_reasons_value jsonb := '[]'::jsonb;
  easy_day_applied_value boolean := false;
  extension_state_value text := 'none';
  extension_source_day_value date := null;
  extension_source_instance_value uuid := null;
  recent_template_ids text[] := array[]::text[];
  ordered_template_ids text[] := array[]::text[];
  filtered_template_ids text[] := array[]::text[];
  selected_template_ids text[] := array[]::text[];
  template_id_value text;
  template_row public.indoor_mission_templates%rowtype;
  existing_instance_count integer := 0;
  source_instance_row public.owner_indoor_mission_instances%rowtype;
  state_row public.owner_indoor_mission_daily_state%rowtype;
  mission_json jsonb := '[]'::jsonb;
  history_json jsonb := '[]'::jsonb;
  reward_scale_value double precision := 1.0;
  adjusted_minimum integer := 1;
  adjusted_reward integer := 0;
  recent_template_id text;
  synthetic_extension jsonb;
begin
  if requester_uid is null then
    raise exception 'permission denied';
  end if;

  select *
  into weather_row
  from public.rpc_get_weather_replacement_summary(
    jsonb_build_object(
      'in_base_risk_level', requested_base_risk,
      'in_now_ts', resolved_now_ts
    )
  )
  limit 1;

  effective_risk_value := coalesce(weather_row.effective_risk_level, requested_base_risk, 'clear');
  replacement_count_value := public.indoor_mission_replacement_count(effective_risk_value);

  age_band_value := public.indoor_mission_age_band(resolved_age_years);
  activity_level_value := public.indoor_mission_activity_level(resolved_recent_daily_minutes);
  walk_frequency_value := public.indoor_mission_walk_frequency_band(resolved_average_weekly_walk_count);

  select ds.applied_multiplier
  into previous_multiplier
  from public.owner_indoor_mission_daily_state ds
  where ds.owner_user_id = requester_uid
    and ds.pet_context_id = resolved_pet_context_id
    and ds.day_key < resolved_day
  order by ds.day_key desc
  limit 1;

  if age_band_value = 'puppy' then
    multiplier_value := multiplier_value - 0.08;
    adjustment_reasons_value := adjustment_reasons_value || jsonb_build_array('유년기 반려견이라 목표를 소폭 완화했어요.');
  elsif age_band_value = 'senior' then
    multiplier_value := multiplier_value - 0.12;
    adjustment_reasons_value := adjustment_reasons_value || jsonb_build_array('노령기 반려견 컨디션을 고려해 목표를 완화했어요.');
  end if;

  if activity_level_value = 'low' then
    multiplier_value := multiplier_value - 0.12;
    adjustment_reasons_value := adjustment_reasons_value || jsonb_build_array('최근 활동량이 낮아 완료 경험 안정화를 위해 목표를 낮췄어요.');
  elsif activity_level_value = 'high' then
    multiplier_value := multiplier_value + 0.10;
    adjustment_reasons_value := adjustment_reasons_value || jsonb_build_array('최근 활동량이 높아 목표를 조금 높였어요.');
  end if;

  if walk_frequency_value = 'sparse' then
    multiplier_value := multiplier_value - 0.08;
    adjustment_reasons_value := adjustment_reasons_value || jsonb_build_array('최근 산책 빈도가 낮아 목표를 완화했어요.');
  elsif walk_frequency_value = 'frequent' then
    multiplier_value := multiplier_value + 0.08;
    adjustment_reasons_value := adjustment_reasons_value || jsonb_build_array('최근 산책 빈도가 높아 목표를 상향했어요.');
  end if;

  multiplier_value := least(greatest(multiplier_value, 0.75), 1.25);
  if previous_multiplier is not null then
    clamped_multiplier_value := least(greatest(multiplier_value, previous_multiplier - 0.15), previous_multiplier + 0.15);
    if abs(clamped_multiplier_value - multiplier_value) > 0.001 then
      adjustment_reasons_value := adjustment_reasons_value || jsonb_build_array('급격한 변동을 막기 위해 일일 변동폭 제한을 적용했어요.');
    end if;
    multiplier_value := clamped_multiplier_value;
  end if;
  multiplier_value := least(greatest(multiplier_value, 0.75), 1.25);

  if abs(multiplier_value - 1.0) < 0.001 then
    adjustment_description_value := '기본 난이도 유지';
  elsif multiplier_value > 1.0 then
    adjustment_description_value := format('기본 대비 +%s%%', round((multiplier_value - 1.0) * 100));
  else
    adjustment_description_value := format('기본 대비 %s%%', round((multiplier_value - 1.0) * 100));
  end if;

  insert into public.owner_indoor_mission_daily_state (
    owner_user_id,
    day_key,
    pet_context_id,
    pet_name_snapshot,
    age_years,
    age_band,
    activity_level,
    walk_frequency,
    applied_multiplier,
    adjustment_description,
    adjustment_reasons,
    easy_day_applied,
    extension_state,
    extension_source_day_key,
    extension_source_instance_id,
    base_risk_level,
    effective_risk_level,
    refreshed_at,
    metadata
  )
  values (
    requester_uid,
    resolved_day,
    resolved_pet_context_id,
    resolved_pet_name,
    resolved_age_years,
    age_band_value,
    activity_level_value,
    walk_frequency_value,
    multiplier_value,
    adjustment_description_value,
    adjustment_reasons_value,
    false,
    'none',
    null,
    null,
    requested_base_risk,
    effective_risk_value,
    resolved_now_ts,
    jsonb_build_object('source', 'rpc_get_indoor_mission_summary')
  )
  on conflict (owner_user_id, day_key, pet_context_id) do update
  set
    pet_name_snapshot = excluded.pet_name_snapshot,
    age_years = excluded.age_years,
    age_band = excluded.age_band,
    activity_level = excluded.activity_level,
    walk_frequency = excluded.walk_frequency,
    applied_multiplier = excluded.applied_multiplier,
    adjustment_description = excluded.adjustment_description,
    adjustment_reasons = excluded.adjustment_reasons,
    base_risk_level = excluded.base_risk_level,
    effective_risk_level = excluded.effective_risk_level,
    refreshed_at = excluded.refreshed_at,
    metadata = coalesce(public.owner_indoor_mission_daily_state.metadata, '{}'::jsonb) || jsonb_build_object('last_refresh_at', resolved_now_ts)
  returning * into state_row;

  easy_day_applied_value := coalesce(state_row.easy_day_applied, false);

  select *
  into state_row
  from public.owner_indoor_mission_daily_state ds
  where ds.owner_user_id = requester_uid
    and ds.day_key = resolved_day
    and ds.pet_context_id = resolved_pet_context_id
  limit 1;

  if state_row.extension_source_instance_id is not null then
    select *
    into source_instance_row
    from public.owner_indoor_mission_instances i
    where i.id = state_row.extension_source_instance_id
    limit 1;

    if source_instance_row.id is not null then
      if source_instance_row.claimed_at is not null or source_instance_row.status = 'claimed' then
        extension_state_value := 'consumed';
      else
        extension_state_value := 'active';
      end if;
      extension_source_day_value := state_row.extension_source_day_key;
      extension_source_instance_value := state_row.extension_source_instance_id;
    else
      extension_state_value := 'none';
      extension_source_day_value := null;
      extension_source_instance_value := null;
    end if;
  else
    select *
    into state_row
    from public.owner_indoor_mission_daily_state ds
    where ds.owner_user_id = requester_uid
      and ds.day_key = (resolved_day - interval '1 day')::date
      and ds.pet_context_id = resolved_pet_context_id
    limit 1;

    if found and state_row.extension_source_instance_id is not null then
      select *
      into source_instance_row
      from public.owner_indoor_mission_instances i
      where i.id = state_row.extension_source_instance_id
      limit 1;

      if source_instance_row.id is not null and (source_instance_row.claimed_at is not null or source_instance_row.status = 'claimed') then
        extension_state_value := 'cooldown';
      else
        extension_state_value := 'expired';
      end if;
    else
      select *
      into source_instance_row
      from public.owner_indoor_mission_instances i
      where i.owner_user_id = requester_uid
        and i.pet_context_id = resolved_pet_context_id
        and i.day_key = (resolved_day - interval '1 day')::date
        and i.is_extension = false
        and coalesce(i.claimed_at, null) is null
      order by i.created_at asc
      limit 1;

      if source_instance_row.id is not null then
        extension_state_value := case
          when source_instance_row.claimed_at is not null then 'consumed'
          else 'active'
        end;
        extension_source_day_value := source_instance_row.day_key;
        extension_source_instance_value := source_instance_row.id;
      else
        extension_state_value := 'none';
      end if;
    end if;

    update public.owner_indoor_mission_daily_state
    set
      extension_state = extension_state_value,
      extension_source_day_key = extension_source_day_value,
      extension_source_instance_id = extension_source_instance_value,
      refreshed_at = resolved_now_ts,
      updated_at = now()
    where owner_user_id = requester_uid
      and day_key = resolved_day
      and pet_context_id = resolved_pet_context_id;
  end if;

  select count(*)::integer
  into existing_instance_count
  from public.owner_indoor_mission_instances i
  where i.owner_user_id = requester_uid
    and i.day_key = resolved_day
    and i.pet_context_id = resolved_pet_context_id
    and i.is_extension = false;

  if existing_instance_count = 0 and replacement_count_value > 0 then
    select coalesce(array_agg(distinct i.template_id), array[]::text[])
    into recent_template_ids
    from public.owner_indoor_mission_instances i
    where i.owner_user_id = requester_uid
      and i.pet_context_id = resolved_pet_context_id
      and i.is_extension = false
      and i.day_key in ((resolved_day - interval '1 day')::date, (resolved_day - interval '2 day')::date);

    select coalesce(array_agg(t.id order by public.indoor_mission_template_priority(t.category, effective_risk_value), t.id), array[]::text[])
    into ordered_template_ids
    from public.indoor_mission_templates t
    where t.is_active is true;

    filtered_template_ids := array[]::text[];
    foreach template_id_value in array ordered_template_ids loop
      if array_position(recent_template_ids, template_id_value) is null then
        filtered_template_ids := array_append(filtered_template_ids, template_id_value);
      end if;
    end loop;

    if coalesce(array_length(filtered_template_ids, 1), 0) < replacement_count_value then
      filtered_template_ids := ordered_template_ids;
    end if;

    selected_template_ids := filtered_template_ids[1:replacement_count_value];
    reward_scale_value := public.indoor_mission_reward_scale(effective_risk_value) * case when easy_day_applied_value then 0.80 else 1.0 end;

    foreach template_id_value in array coalesce(selected_template_ids, array[]::text[]) loop
      select *
      into template_row
      from public.indoor_mission_templates t
      where t.id = template_id_value
      limit 1;

      if template_row.id is null then
        continue;
      end if;

      adjusted_minimum := greatest(1, round(template_row.minimum_action_count * multiplier_value)::integer);
      adjusted_reward := greatest(1, round(template_row.base_reward_points * reward_scale_value)::integer);

      insert into public.owner_indoor_mission_instances (
        owner_user_id,
        day_key,
        pet_context_id,
        instance_key,
        template_id,
        category,
        title_snapshot,
        description_snapshot,
        minimum_action_count_snapshot,
        reward_points_snapshot,
        streak_eligible_snapshot,
        action_count,
        status,
        is_extension,
        extension_source_day_key,
        extension_reward_scale,
        metadata
      )
      values (
        requester_uid,
        resolved_day,
        resolved_pet_context_id,
        concat(to_char(resolved_day, 'YYYY-MM-DD'), '|', resolved_pet_context_id, '|', template_row.id, '|base'),
        template_row.id,
        template_row.category,
        template_row.title,
        template_row.description,
        adjusted_minimum,
        adjusted_reward,
        template_row.streak_eligible,
        0,
        'active',
        false,
        null,
        1.0,
        jsonb_build_object(
          'base_risk_level', requested_base_risk,
          'effective_risk_level', effective_risk_value,
          'applied_multiplier', multiplier_value,
          'easy_day_applied', easy_day_applied_value,
          'issued_at', resolved_now_ts
        )
      )
      on conflict (instance_key) do nothing;
    end loop;
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'dayKey', to_char(h.day_key, 'YYYY-MM-DD'),
        'petId', case when h.pet_context_id = '__none__' then null else h.pet_context_id end,
        'petName', h.pet_name_snapshot,
        'multiplier', h.applied_multiplier,
        'ageBand', h.age_band,
        'activityLevel', h.activity_level,
        'walkFrequency', h.walk_frequency,
        'easyDayApplied', h.easy_day_applied
      )
      order by h.day_key desc
    ),
    '[]'::jsonb
  )
  into history_json
  from (
    select ds.*
    from public.owner_indoor_mission_daily_state ds
    where ds.owner_user_id = requester_uid
      and ds.pet_context_id = resolved_pet_context_id
    order by ds.day_key desc
    limit 5
  ) h;

  mission_json := '[]'::jsonb;
  if extension_source_instance_value is not null and extension_state_value in ('active', 'consumed') then
    select *
    into source_instance_row
    from public.owner_indoor_mission_instances i
    where i.id = extension_source_instance_value
    limit 1;

    if source_instance_row.id is not null then
      synthetic_extension := jsonb_build_object(
        'missionInstanceId', source_instance_row.id,
        'templateId', source_instance_row.template_id,
        'category', source_instance_row.category,
        'title', source_instance_row.title_snapshot,
        'description', source_instance_row.description_snapshot,
        'minimumActionCount', source_instance_row.minimum_action_count_snapshot,
        'rewardPoint', greatest(1, round((
          (select t.base_reward_points from public.indoor_mission_templates t where t.id = source_instance_row.template_id)
          * public.indoor_mission_reward_scale(effective_risk_value)
          * case when easy_day_applied_value then 0.80 else 1.0 end
          * 0.70
        ))::integer),
        'streakEligible', false,
        'trackingDayKey', to_char(source_instance_row.day_key, 'YYYY-MM-DD'),
        'isExtension', true,
        'extensionSourceDayKey', to_char(source_instance_row.day_key, 'YYYY-MM-DD'),
        'extensionRewardScale', 0.70,
        'actionCount', source_instance_row.action_count,
        'claimable', source_instance_row.claimed_at is null and source_instance_row.action_count >= source_instance_row.minimum_action_count_snapshot,
        'rewardEligible', source_instance_row.claimed_at is null and source_instance_row.action_count >= source_instance_row.minimum_action_count_snapshot,
        'claimedAt', source_instance_row.claimed_at,
        'status', case when source_instance_row.claimed_at is not null then 'claimed' else 'active' end
      );
      mission_json := mission_json || jsonb_build_array(synthetic_extension);
    end if;
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'missionInstanceId', i.id,
        'templateId', i.template_id,
        'category', i.category,
        'title', i.title_snapshot,
        'description', i.description_snapshot,
        'minimumActionCount', i.minimum_action_count_snapshot,
        'rewardPoint', i.reward_points_snapshot,
        'streakEligible', i.streak_eligible_snapshot,
        'trackingDayKey', to_char(i.day_key, 'YYYY-MM-DD'),
        'isExtension', i.is_extension,
        'extensionSourceDayKey', case when i.extension_source_day_key is null then null else to_char(i.extension_source_day_key, 'YYYY-MM-DD') end,
        'extensionRewardScale', i.extension_reward_scale,
        'actionCount', i.action_count,
        'claimable', i.claimed_at is null and i.action_count >= i.minimum_action_count_snapshot,
        'rewardEligible', i.claimed_at is null and i.action_count >= i.minimum_action_count_snapshot,
        'claimedAt', i.claimed_at,
        'status', i.status
      )
      order by i.created_at asc
    ),
    '[]'::jsonb
  )
  into mission_json
  from (
    select *
    from public.owner_indoor_mission_instances i
    where i.owner_user_id = requester_uid
      and i.day_key = resolved_day
      and i.pet_context_id = resolved_pet_context_id
      and i.is_extension = false
      and (i.status in ('active', 'claimed') or (i.action_count >= i.minimum_action_count_snapshot and i.claimed_at is null))
    order by i.created_at asc
  ) i;

  if extension_source_instance_value is not null and extension_state_value in ('active', 'consumed') then
    select *
    into source_instance_row
    from public.owner_indoor_mission_instances i
    where i.id = extension_source_instance_value
    limit 1;
    if source_instance_row.id is not null then
      mission_json := jsonb_build_array(
        jsonb_build_object(
          'missionInstanceId', source_instance_row.id,
          'templateId', source_instance_row.template_id,
          'category', source_instance_row.category,
          'title', source_instance_row.title_snapshot,
          'description', source_instance_row.description_snapshot,
          'minimumActionCount', source_instance_row.minimum_action_count_snapshot,
          'rewardPoint', greatest(1, round((
            (select t.base_reward_points from public.indoor_mission_templates t where t.id = source_instance_row.template_id)
            * public.indoor_mission_reward_scale(effective_risk_value)
            * case when easy_day_applied_value then 0.80 else 1.0 end
            * 0.70
          ))::integer),
          'streakEligible', false,
          'trackingDayKey', to_char(source_instance_row.day_key, 'YYYY-MM-DD'),
          'isExtension', true,
          'extensionSourceDayKey', to_char(source_instance_row.day_key, 'YYYY-MM-DD'),
          'extensionRewardScale', 0.70,
          'actionCount', source_instance_row.action_count,
          'claimable', source_instance_row.claimed_at is null and source_instance_row.action_count >= source_instance_row.minimum_action_count_snapshot,
          'rewardEligible', source_instance_row.claimed_at is null and source_instance_row.action_count >= source_instance_row.minimum_action_count_snapshot,
          'claimedAt', source_instance_row.claimed_at,
          'status', case when source_instance_row.claimed_at is not null then 'claimed' else 'active' end
        )
      ) || mission_json;
    end if;
  end if;

  return query
  select
    requester_uid,
    resolved_pet_context_id,
    to_char(resolved_day, 'YYYY-MM-DD'),
    requested_base_risk,
    effective_risk_value,
    extension_state_value,
    public.indoor_mission_extension_message(extension_state_value),
    resolved_pet_name,
    age_band_value,
    activity_level_value,
    walk_frequency_value,
    multiplier_value,
    adjustment_description_value,
    adjustment_reasons_value,
    case when easy_day_applied_value then 'active' else case when resolved_pet_context_id = '__none__' then 'unavailable' else 'available' end end,
    public.indoor_mission_easy_day_message(easy_day_applied_value),
    history_json,
    mission_json,
    resolved_now_ts;
end;
$$;

grant execute on function public.rpc_get_indoor_mission_summary(jsonb) to authenticated, service_role;

create or replace function public.rpc_record_indoor_mission_action(payload jsonb)
returns table (
  mission_instance_id uuid,
  template_id text,
  event_id text,
  idempotent boolean,
  action_count integer,
  minimum_action_count integer,
  claimable boolean,
  status text,
  refreshed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_uid uuid := auth.uid();
  resolved_now_ts timestamptz := coalesce(
    nullif(payload ->> 'now_ts', '')::timestamptz,
    nullif(payload ->> 'in_now_ts', '')::timestamptz,
    now()
  );
  target_instance_id uuid := coalesce(
    nullif(payload ->> 'mission_instance_id', '')::uuid,
    nullif(payload ->> 'in_mission_instance_id', '')::uuid
  );
  normalized_event_id text := coalesce(
    nullif(trim(coalesce(payload ->> 'event_id', payload ->> 'in_event_id', payload ->> 'request_id', payload ->> 'in_request_id')), ''),
    gen_random_uuid()::text
  );
  instance_row public.owner_indoor_mission_instances%rowtype;
  inserted_id bigint;
  next_action_count integer;
begin
  if requester_uid is null then
    raise exception 'permission denied';
  end if;
  if target_instance_id is null then
    raise exception 'mission_instance_id is required';
  end if;

  select *
  into instance_row
  from public.owner_indoor_mission_instances i
  where i.id = target_instance_id
  for update;

  if instance_row.id is null then
    raise exception 'indoor mission instance not found';
  end if;
  if instance_row.owner_user_id <> requester_uid then
    raise exception 'forbidden indoor mission access';
  end if;

  insert into public.owner_indoor_mission_action_events (
    owner_user_id,
    mission_instance_id,
    event_id,
    delta_value,
    payload,
    recorded_at
  )
  values (
    requester_uid,
    instance_row.id,
    normalized_event_id,
    1,
    coalesce(payload, '{}'::jsonb),
    resolved_now_ts
  )
  on conflict (mission_instance_id, event_id) do nothing
  returning id into inserted_id;

  if inserted_id is not null and instance_row.claimed_at is null then
    next_action_count := instance_row.action_count + 1;
    update public.owner_indoor_mission_instances
    set
      action_count = next_action_count,
      updated_at = now()
    where id = instance_row.id
    returning * into instance_row;
  end if;

  return query
  select
    instance_row.id,
    instance_row.template_id,
    normalized_event_id,
    inserted_id is null,
    instance_row.action_count,
    instance_row.minimum_action_count_snapshot,
    instance_row.claimed_at is null and instance_row.action_count >= instance_row.minimum_action_count_snapshot,
    instance_row.status,
    resolved_now_ts;
end;
$$;

grant execute on function public.rpc_record_indoor_mission_action(jsonb) to authenticated, service_role;

create or replace function public.rpc_claim_indoor_mission_reward(payload jsonb)
returns table (
  mission_instance_id uuid,
  template_id text,
  claim_status text,
  already_claimed boolean,
  reward_points integer,
  claimed_at timestamptz,
  refreshed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_uid uuid := auth.uid();
  resolved_now_ts timestamptz := coalesce(
    nullif(payload ->> 'now_ts', '')::timestamptz,
    nullif(payload ->> 'in_now_ts', '')::timestamptz,
    now()
  );
  target_instance_id uuid := coalesce(
    nullif(payload ->> 'mission_instance_id', '')::uuid,
    nullif(payload ->> 'in_mission_instance_id', '')::uuid
  );
  normalized_request_id text := coalesce(
    nullif(trim(coalesce(payload ->> 'request_id', payload ->> 'in_request_id')), ''),
    gen_random_uuid()::text
  );
  resolved_day date := public.normalize_indoor_mission_day_key(
    coalesce(payload ->> 'day_key', payload ->> 'in_day_key'),
    resolved_now_ts
  );
  resolved_pet_context_id text := public.normalize_indoor_mission_pet_context_id(
    coalesce(payload ->> 'pet_context_id', payload ->> 'in_pet_context_id')
  );
  instance_row public.owner_indoor_mission_instances%rowtype;
  claim_row public.owner_indoor_mission_claims%rowtype;
  state_row public.owner_indoor_mission_daily_state%rowtype;
  effective_reward integer;
begin
  if requester_uid is null then
    raise exception 'permission denied';
  end if;
  if target_instance_id is null then
    raise exception 'mission_instance_id is required';
  end if;

  select *
  into instance_row
  from public.owner_indoor_mission_instances i
  where i.id = target_instance_id
  for update;

  if instance_row.id is null then
    raise exception 'indoor mission instance not found';
  end if;
  if instance_row.owner_user_id <> requester_uid then
    raise exception 'forbidden indoor mission access';
  end if;

  if instance_row.claimed_at is not null or instance_row.status = 'claimed' then
    select *
    into claim_row
    from public.owner_indoor_mission_claims c
    where c.mission_instance_id = instance_row.id
    limit 1;

    return query
    select
      instance_row.id,
      instance_row.template_id,
      coalesce(claim_row.claim_status, 'claimed'),
      true,
      coalesce(claim_row.reward_points, instance_row.reward_points_snapshot),
      coalesce(claim_row.claimed_at, instance_row.claimed_at),
      resolved_now_ts;
    return;
  end if;

  if instance_row.action_count < instance_row.minimum_action_count_snapshot then
    return query
    select
      instance_row.id,
      instance_row.template_id,
      'rejected',
      false,
      instance_row.reward_points_snapshot,
      null::timestamptz,
      resolved_now_ts;
    return;
  end if;

  effective_reward := instance_row.reward_points_snapshot;

  select *
  into state_row
  from public.owner_indoor_mission_daily_state ds
  where ds.owner_user_id = requester_uid
    and ds.day_key = resolved_day
    and ds.pet_context_id = resolved_pet_context_id
  limit 1;

  if state_row.extension_source_instance_id = instance_row.id then
    effective_reward := greatest(1, round((
      (select t.base_reward_points from public.indoor_mission_templates t where t.id = instance_row.template_id)
      * public.indoor_mission_reward_scale(coalesce(state_row.effective_risk_level, 'clear'))
      * case when coalesce(state_row.easy_day_applied, false) then 0.80 else 1.0 end
      * 0.70
    ))::integer);
  end if;

  insert into public.owner_indoor_mission_claims (
    owner_user_id,
    mission_instance_id,
    request_id,
    claim_status,
    reward_points,
    claimed_at,
    payload
  )
  values (
    requester_uid,
    instance_row.id,
    normalized_request_id,
    'claimed',
    effective_reward,
    resolved_now_ts,
    jsonb_build_object('requested_at', resolved_now_ts)
  )
  on conflict (mission_instance_id) do nothing
  returning * into claim_row;

  if claim_row.id is null then
    select *
    into claim_row
    from public.owner_indoor_mission_claims c
    where c.mission_instance_id = instance_row.id
    limit 1;

    return query
    select
      instance_row.id,
      instance_row.template_id,
      coalesce(claim_row.claim_status, 'claimed'),
      true,
      coalesce(claim_row.reward_points, effective_reward),
      coalesce(claim_row.claimed_at, resolved_now_ts),
      resolved_now_ts;
    return;
  end if;

  update public.owner_indoor_mission_instances
  set
    status = 'claimed',
    claimed_at = resolved_now_ts,
    updated_at = now()
  where id = instance_row.id
  returning * into instance_row;

  if state_row.extension_source_instance_id = instance_row.id then
    update public.owner_indoor_mission_daily_state
    set
      extension_state = 'consumed',
      refreshed_at = resolved_now_ts,
      updated_at = now()
    where owner_user_id = requester_uid
      and day_key = resolved_day
      and pet_context_id = resolved_pet_context_id;
  end if;

  return query
  select
    instance_row.id,
    instance_row.template_id,
    claim_row.claim_status,
    false,
    claim_row.reward_points,
    claim_row.claimed_at,
    resolved_now_ts;
end;
$$;

grant execute on function public.rpc_claim_indoor_mission_reward(jsonb) to authenticated, service_role;

create or replace function public.rpc_activate_indoor_easy_day(payload jsonb)
returns table (
  outcome text,
  pet_context_id text,
  already_applied boolean,
  refreshed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_uid uuid := auth.uid();
  resolved_now_ts timestamptz := coalesce(
    nullif(payload ->> 'now_ts', '')::timestamptz,
    nullif(payload ->> 'in_now_ts', '')::timestamptz,
    now()
  );
  resolved_day date := public.normalize_indoor_mission_day_key(
    coalesce(payload ->> 'day_key', payload ->> 'in_day_key'),
    resolved_now_ts
  );
  resolved_pet_context_id text := public.normalize_indoor_mission_pet_context_id(
    coalesce(payload ->> 'pet_context_id', payload ->> 'in_pet_context_id')
  );
  state_row public.owner_indoor_mission_daily_state%rowtype;
  current_reward_scale double precision;
begin
  if requester_uid is null then
    raise exception 'permission denied';
  end if;
  if resolved_pet_context_id = '__none__' then
    return query select 'missing_pet', resolved_pet_context_id, false, resolved_now_ts;
    return;
  end if;

  perform public.rpc_get_indoor_mission_summary(
    jsonb_build_object(
      'in_day_key', to_char(resolved_day, 'YYYY-MM-DD'),
      'in_pet_context_id', resolved_pet_context_id,
      'in_pet_name', coalesce(payload ->> 'pet_name', payload ->> 'in_pet_name', '강아지'),
      'in_age_years', payload ->> 'age_years',
      'in_recent_daily_minutes', coalesce(payload ->> 'recent_daily_minutes', payload ->> 'in_recent_daily_minutes', '0'),
      'in_average_weekly_walk_count', coalesce(payload ->> 'average_weekly_walk_count', payload ->> 'in_average_weekly_walk_count', '0'),
      'in_base_risk_level', coalesce(payload ->> 'base_risk_level', payload ->> 'in_base_risk_level', 'clear'),
      'in_now_ts', resolved_now_ts
    )
  );

  select *
  into state_row
  from public.owner_indoor_mission_daily_state ds
  where ds.owner_user_id = requester_uid
    and ds.day_key = resolved_day
    and ds.pet_context_id = resolved_pet_context_id
  for update;

  if state_row.easy_day_applied then
    return query select 'already_used', resolved_pet_context_id, true, resolved_now_ts;
    return;
  end if;

  update public.owner_indoor_mission_daily_state
  set
    easy_day_applied = true,
    easy_day_activated_at = resolved_now_ts,
    refreshed_at = resolved_now_ts,
    updated_at = now()
  where owner_user_id = requester_uid
    and day_key = resolved_day
    and pet_context_id = resolved_pet_context_id
  returning * into state_row;

  current_reward_scale := public.indoor_mission_reward_scale(coalesce(state_row.effective_risk_level, 'clear')) * 0.80;

  update public.owner_indoor_mission_instances
  set
    reward_points_snapshot = greatest(1, round((
      (select t.base_reward_points from public.indoor_mission_templates t where t.id = public.owner_indoor_mission_instances.template_id)
      * current_reward_scale
    ))::integer),
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('easy_day_applied', true),
    updated_at = now()
  where owner_user_id = requester_uid
    and day_key = resolved_day
    and pet_context_id = resolved_pet_context_id
    and is_extension = false
    and claimed_at is null;

  return query select 'activated', resolved_pet_context_id, false, resolved_now_ts;
end;
$$;

grant execute on function public.rpc_activate_indoor_easy_day(jsonb) to authenticated, service_role;
