-- DogArea initial remote schema for Supabase migration.
-- Phase 1: one walk belongs to one pet.
-- Phase 2 placeholder: walk_session_pets supports N:M multi-dog walks.

create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  profile_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pets (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  photo_url text,
  caricature_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.walk_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  pet_id uuid not null references public.pets(id) on delete restrict,
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_sec integer not null default 0 check (duration_sec >= 0),
  area_m2 double precision not null default 0 check (area_m2 >= 0),
  map_image_url text,
  source_device text not null default 'ios' check (source_device in ('ios', 'watchos', 'imported')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.walk_points (
  id bigint generated by default as identity primary key,
  walk_session_id uuid not null references public.walk_sessions(id) on delete cascade,
  seq_no integer not null check (seq_no >= 0),
  lat double precision not null,
  lng double precision not null,
  recorded_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (walk_session_id, seq_no)
);

create table if not exists public.area_milestones (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  pet_id uuid references public.pets(id) on delete set null,
  area_name text not null,
  area_m2 double precision not null check (area_m2 >= 0),
  achieved_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.walk_session_pets (
  walk_session_id uuid not null references public.walk_sessions(id) on delete cascade,
  pet_id uuid not null references public.pets(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (walk_session_id, pet_id)
);

create index if not exists idx_pets_owner_user_id on public.pets(owner_user_id);
create index if not exists idx_walk_sessions_owner_user_id on public.walk_sessions(owner_user_id);
create index if not exists idx_walk_sessions_pet_id on public.walk_sessions(pet_id);
create index if not exists idx_walk_points_walk_session_id on public.walk_points(walk_session_id);
create index if not exists idx_area_milestones_owner_user_id on public.area_milestones(owner_user_id);
create index if not exists idx_area_milestones_pet_id on public.area_milestones(pet_id);

-- Keep updated_at maintained by trigger.
drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_pets_set_updated_at on public.pets;
create trigger trg_pets_set_updated_at
before update on public.pets
for each row
execute function public.set_updated_at();

drop trigger if exists trg_walk_sessions_set_updated_at on public.walk_sessions;
create trigger trg_walk_sessions_set_updated_at
before update on public.walk_sessions
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.pets enable row level security;
alter table public.walk_sessions enable row level security;
alter table public.walk_points enable row level security;
alter table public.area_milestones enable row level security;
alter table public.walk_session_pets enable row level security;

-- profiles policies
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- pets policies
drop policy if exists pets_select_own on public.pets;
create policy pets_select_own
on public.pets
for select
to authenticated
using (owner_user_id = auth.uid());

drop policy if exists pets_insert_own on public.pets;
create policy pets_insert_own
on public.pets
for insert
to authenticated
with check (owner_user_id = auth.uid());

drop policy if exists pets_update_own on public.pets;
create policy pets_update_own
on public.pets
for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

drop policy if exists pets_delete_own on public.pets;
create policy pets_delete_own
on public.pets
for delete
to authenticated
using (owner_user_id = auth.uid());

-- walk_sessions policies
drop policy if exists walk_sessions_select_own on public.walk_sessions;
create policy walk_sessions_select_own
on public.walk_sessions
for select
to authenticated
using (owner_user_id = auth.uid());

drop policy if exists walk_sessions_insert_own on public.walk_sessions;
create policy walk_sessions_insert_own
on public.walk_sessions
for insert
to authenticated
with check (
  owner_user_id = auth.uid()
  and exists (
    select 1
    from public.pets p
    where p.id = pet_id
      and p.owner_user_id = auth.uid()
  )
);

drop policy if exists walk_sessions_update_own on public.walk_sessions;
create policy walk_sessions_update_own
on public.walk_sessions
for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

drop policy if exists walk_sessions_delete_own on public.walk_sessions;
create policy walk_sessions_delete_own
on public.walk_sessions
for delete
to authenticated
using (owner_user_id = auth.uid());

-- walk_points policies: parent session ownership check
drop policy if exists walk_points_select_own on public.walk_points;
create policy walk_points_select_own
on public.walk_points
for select
to authenticated
using (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
);

drop policy if exists walk_points_insert_own on public.walk_points;
create policy walk_points_insert_own
on public.walk_points
for insert
to authenticated
with check (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
);

drop policy if exists walk_points_update_own on public.walk_points;
create policy walk_points_update_own
on public.walk_points
for update
to authenticated
using (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
);

drop policy if exists walk_points_delete_own on public.walk_points;
create policy walk_points_delete_own
on public.walk_points
for delete
to authenticated
using (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
);

-- area_milestones policies
drop policy if exists area_milestones_select_own on public.area_milestones;
create policy area_milestones_select_own
on public.area_milestones
for select
to authenticated
using (owner_user_id = auth.uid());

drop policy if exists area_milestones_insert_own on public.area_milestones;
create policy area_milestones_insert_own
on public.area_milestones
for insert
to authenticated
with check (owner_user_id = auth.uid());

drop policy if exists area_milestones_update_own on public.area_milestones;
create policy area_milestones_update_own
on public.area_milestones
for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

drop policy if exists area_milestones_delete_own on public.area_milestones;
create policy area_milestones_delete_own
on public.area_milestones
for delete
to authenticated
using (owner_user_id = auth.uid());

-- walk_session_pets policies (phase 2 reserved)
drop policy if exists walk_session_pets_select_own on public.walk_session_pets;
create policy walk_session_pets_select_own
on public.walk_session_pets
for select
to authenticated
using (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
);

drop policy if exists walk_session_pets_insert_own on public.walk_session_pets;
create policy walk_session_pets_insert_own
on public.walk_session_pets
for insert
to authenticated
with check (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
  and exists (
    select 1
    from public.pets p
    where p.id = pet_id
      and p.owner_user_id = auth.uid()
  )
);

drop policy if exists walk_session_pets_delete_own on public.walk_session_pets;
create policy walk_session_pets_delete_own
on public.walk_session_pets
for delete
to authenticated
using (
  exists (
    select 1
    from public.walk_sessions s
    where s.id = walk_session_id
      and s.owner_user_id = auth.uid()
  )
);
